version:     "002--19-September-2021"
copyright:   "2021-2021"
description:
  This is 
  anantaristik
disclaimer:
  I have spoken.
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "https://anantaristik.github.io/os212/"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "TarBall"
  link:      "https://os.vlsm.org/Log/anantaristik.tar.bz2.txt"
- navbar:    "GitHub"
  link:      "https://github.com/anantaristik"
- navbar:    "Listing"
  link:      "/000.html"
- navbar:    "About"
  link:      "/ABOUT/"
title:       "anantaristik page"
lang:        "en-US"
author:      "Ananta"
address:     "Chronos, Computer Science, University of Indonesia"
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://template.vlsm.org/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/anantaristik"


